name: "Check PR content"
on: 
  pull_request:
      types: [opened, edited, assigned, closed, review_requested, ready_for_review]
      paths:
        - index.html

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v10
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        bodyDoesNotContain: ''
        bodyContains: ''
        diffContains: ''
        diffDoesNotContain: " must | must not | should | should not | may"